window.addEventListener("load", () => {
  const imagesToPreload = [
    "/assets/images/tarot/swords/four_of_swords.png",
    "/assets/images/tarot/swords/seven_of_swords.png",
    "/assets/images/tarot/swords/three_of_swords.png",
    "/assets/images/tarot/swords/six_of_swords.png",
    "/assets/images/tarot/swords/two_of_swords.png",
    "/assets/images/tarot/swords/knight_of_swords.png",
    "/assets/images/tarot/swords/eight_of_swords.png",
    "/assets/images/tarot/swords/nine_of_swords.png",
    "/assets/images/tarot/swords/page_of_swords.png",
    "/assets/images/tarot/swords/ace_of_swords.png",
    "/assets/images/tarot/swords/five_of_swords.png",
    "/assets/images/tarot/swords/king_of_swords.png",
    "/assets/images/tarot/swords/queen_of_swords.png",
    "/assets/images/tarot/swords/ten_of_swords.png",
    "/assets/images/tarot/cups/nine_of_cups.png",
    "/assets/images/tarot/cups/four_of_cups.png",
    "/assets/images/tarot/cups/five_of_cups.png",
    "/assets/images/tarot/cups/two_of_cups.png",
    "/assets/images/tarot/cups/knight_of_cups.png",
    "/assets/images/tarot/cups/queen_of_cups.png",
    "/assets/images/tarot/cups/page_of_cups.png",
    "/assets/images/tarot/cups/ten_of_cups.png",
    "/assets/images/tarot/cups/eight_of_cups.png",
    "/assets/images/tarot/cups/king_of_cups.png",
    "/assets/images/tarot/cups/six_of_cups.png",
    "/assets/images/tarot/cups/ace_of_cups.png",
    "/assets/images/tarot/cups/seven_of_cups.png",
    "/assets/images/tarot/cups/three_of_cups.png",
    "/assets/images/tarot/major_arcana/the_world.png",
    "/assets/images/tarot/major_arcana/the_magician.png",
    "/assets/images/tarot/major_arcana/the_tower.png",
    "/assets/images/tarot/major_arcana/the_emperor.png",
    "/assets/images/tarot/major_arcana/the_empress.png",
    "/assets/images/tarot/major_arcana/the_hermit.png",
    "/assets/images/tarot/major_arcana/the_devil.png",
    "/assets/images/tarot/major_arcana/the_star.png",
    "/assets/images/tarot/major_arcana/temperance.png",
    "/assets/images/tarot/major_arcana/justice.png",
    "/assets/images/tarot/major_arcana/the_hanged_man.png",
    "/assets/images/tarot/major_arcana/the_hierophant.png",
    "/assets/images/tarot/major_arcana/the_high_priestess.png",
    "/assets/images/tarot/major_arcana/judgement.png",
    "/assets/images/tarot/major_arcana/strength.png",
    "/assets/images/tarot/major_arcana/the_fool.png",
    "/assets/images/tarot/major_arcana/the_moon.png",
    "/assets/images/tarot/major_arcana/the_chariot.png",
    "/assets/images/tarot/major_arcana/death.png",
    "/assets/images/tarot/major_arcana/the_lovers.png",
    "/assets/images/tarot/major_arcana/the_sun.png",
    "/assets/images/tarot/major_arcana/wheel_of_fortune.png",
    "/assets/images/tarot/pentacles/seven_of_pentacles.png",
    "/assets/images/tarot/pentacles/six_of_pentacles.png",
    "/assets/images/tarot/pentacles/knight_of_pentacles.png",
    "/assets/images/tarot/pentacles/five_of_pentacles.png",
    "/assets/images/tarot/pentacles/ten_of_pentacles.png",
    "/assets/images/tarot/pentacles/three_of_pentacles.png",
    "/assets/images/tarot/pentacles/page_of_pentacles.png",
    "/assets/images/tarot/pentacles/queen_of_pentacles.png",
    "/assets/images/tarot/pentacles/ace_of_pentacles.png",
    "/assets/images/tarot/pentacles/eight_of_pentacles.png",
    "/assets/images/tarot/pentacles/nine_of_pentacles.png",
    "/assets/images/tarot/pentacles/two_of_pentacles.png",
    "/assets/images/tarot/pentacles/four_of_pentacles.png",
    "/assets/images/tarot/pentacles/king_of_pentacles.png",
    "/assets/images/tarot/wands/king_of_wands.png",
    "/assets/images/tarot/wands/queen_of_wands.png",
    "/assets/images/tarot/wands/eight_of_wands.png",
    "/assets/images/tarot/wands/ace_of_wands.png",
    "/assets/images/tarot/wands/two_of_wands.png",
    "/assets/images/tarot/wands/nine_of_wands.png",
    "/assets/images/tarot/wands/ten_of_wands.png",
    "/assets/images/tarot/wands/six_of_wands.png",
    "/assets/images/tarot/wands/five_of_wands.png",
    "/assets/images/tarot/wands/three_of_wands.png",
    "/assets/images/tarot/wands/knight_of_wands.png",
    "/assets/images/tarot/wands/seven_of_wands.png",
    "/assets/images/tarot/wands/page_of_wands.png",
    "/assets/images/tarot/wands/four_of_wands.png"
  ];

  imagesToPreload.forEach(src => {
    fetch(src, { cache: "force-cache" })
      .then(response => response.blob())
      .then(blob => {
        const img = new Image();
        img.src = URL.createObjectURL(blob);
      })
      .catch(err => console.error("Preloading failed", err));
  });
});
